

1.   Dos motos viajan a diferentes velocidades (**vel1** y **vel2**) y están distanciados por una distancia **dis**. La moto que se encuentra detrás lleva una velocidad mayor que la primera. Se pide realizar un script en python que solicite al usuario la distancia entre las motos en km y las velocidades de las mismas y con ello devolver en cuanto tiempo la moto 2 alcanzará a la moto 1.

In [ ]:
#declaración de variables
vel1 = float(input("Introduce la velocidad de la moto uno: "))
vel2 = float(input("Introduce la velocidad de la moto dos: "))
d = float(input("Introduce la distancia entre la moto 1 y la moto dos(KM): "))

#Condicional que se asegura de que la moto 2 siempre sea más rápida
if vel2<=vel1:
  print("La moto2 siempre ha de ir más rápido que la moto uno, intorduce otra velocidad")
else:
  tiempo = int(d / (vel2-vel1))
  print(f"La moto 1 ha sido alcanzada en {tiempo} horas")

Introduce la velocidad de la moto uno: 50
Introduce la velocidad de la moto dos: 60
Introduce la distancia entre la moto 1 y la moto dos(KM): 43
La moto 1 ha sido alcanzada en 4 horas


2. El tutor de 2º ASIR esta organizando un viaje a Granada, y requiere determinar cuánto debe cobrar a cada alumne y cuánto debe pagar a la agencia de viajes. La forma de cobrar es la siguiente: si son 100 alumnos o más, el costo por cada alumno es de 65 euros; de 50 a 99 alumnos, el costo es de 70 euros, de 30 a 49, de 95 euros, y si son menos de 30, el costo de la guagua es de 4000 euros, sin importar el número de alumnos. Realice un script que permita determinar el pago a la compañía de guaguas y lo que debe pagar cada alumno por el viaje.

In [ ]:
#declaración variable
numalums= int(input("Introduce el número de alumnos que se van a Granada: "))

#condicional
if numalums>=100:
  print("Cada alumno deberá pagar 100 euros.")
elif numalums>=50:
    print("Cada alumno deberá pagar 65 euros.")
elif numalums>=30:
    print("Cada alumno deberá pagar 100 euros.")
else:
  print("El costo de guagua es de 4000 euros.")



3. Crea un script que permita adivinar un número. La aplicación genera un número aleatorio del 1 al 100. A continuación va pidiendo números y va respondiendo si el número a adivinar es mayor o menor que el introducido, además de los intentos que te quedan (tienes 10 intentos para acertarlo).  El programa termina cuando se acierta el número (además te dice en cuantos  intentos lo has acertado), si se llega al limite de intentos te muestra el  número que había generado.

In [ ]:
import random
randn=random.randint(1,100)
cont=int(0)

while advn != randn:
 advn=int(input("Introduce un número para adivinar el número generado: "))
 if advn < randn:
   print("El número introducido es menor al generado.")
   cont+=1
 elif advn > randn:
   print("El número introducido es mayor al generado.")
   cont+=1
 else:
   print(f"Exacto, el número era {advn} y lo has adivinado en {cont} intentos.")


Introduce un número para adivinar el número generado: 10
El número introducido es menor al generado.
Introduce un número para adivinar el número generado: 100
El número introducido es mayor al generado.
Introduce un número para adivinar el número generado: 40
El número introducido es menor al generado.
Introduce un número para adivinar el número generado: 50
El número introducido es menor al generado.
Introduce un número para adivinar el número generado: 90
El número introducido es mayor al generado.
Introduce un número para adivinar el número generado: 80
El número introducido es menor al generado.
Introduce un número para adivinar el número generado: 81
El número introducido es menor al generado.
Introduce un número para adivinar el número generado: 85
El número introducido es menor al generado.
Introduce un número para adivinar el número generado: 84
El número introducido es menor al generado.
Introduce un número para adivinar el número generado: 83
El número introducido es menor al

4. Realizar un script que pida una String por teclado que contenga espacios y devuelva el número de palabrás que contenga

In [ ]:
frase=str(input("Introuce una frase: "))
cont=int(0)

palabra=frase.split()

for i in palabra:
  cont+=1
if cont == 1:
  print("Solo ha introducido una palabra.")
else:
  print(cont)

Introuce una frase: hola
Solo ha introducido una palabra.


5. Realiza un script que se le pasen 5 notas de un alumno por teclado (comprendidas entre 0 y 10). A continuación debe mostrar todas las notas, la nota media, la nota más alta que ha sacado y la menor.



In [ ]:
lista=list()
import random
import statistics
for i in range(5):
  randn=random.randint(0,10)
  lista.append(randn)
print(f"La nota media es: {statistics.mean(lista)}")
print( )
print(f"La nota más alta es: {max(lista)}")
print( )
print(f"La nota más baja es: {min(lista)}")

La nota media es: 2.8

La nota más alta es: 7

La nota más baja es: 0


6. Realizar un script que cree una una tabla bidimensional de 5x5 y nombre 'diagonal'. La Componentes de han de empezar por 1 incrementandola hata estar llena la matirz. Se ha de mostrar el contenido de la tabla por pantalla.

In [ ]:

import numpy as np

# Crear una matriz de 5x5 llena de ceros

tabla = np.array[[j*6+i+1 for j in range(6)] for n in range(6)]
tabla2 = [ ]

# Rellenar las diagonales con 1s

for fila in tabla:
    print(" ".join(map(str, fila)))
    tabla2 += fila

tab = sp.Matrix([[0 for _ in range(5)] for _ in range(5)])

det = tab.det()
print(det)






1 2 3 4 5 6
7 8 9 10 11 12
13 14 15 16 17 18
19 20 21 22 23 24
25 26 27 28 29 30
31 32 33 34 35 36
0


In [ ]:
!pip install sympy

7. Crea un script que pida un número y cree un diccionario cuyas claves sean desde el número 1 hasta el número indicado, y los valores sean los cuadrados de las claves.



In [ ]:
import math
num=int(input("Inserta un número: "))
dict1 = { }

for i in range(1,num + 1):
  dict1[i] = [i ** 2]

print(dict1)

Inserta un número: 10
{1: [1], 2: [4], 3: [9], 4: [16], 5: [25], 6: [36], 7: [49], 8: [64], 9: [81]}


8. Crea un script de una agenda en la que se guardan nombres y números de teléfono. En la agenda existirá un menú con las siguientes opciones:
 * **Añadir/modificar**: Nos pide un nombre. Si el nombre se encuentra en la agenda, debe mostrar el teléfono y, opcionalmente, permitir modificarlo si no es correcto. Si el nombre no se encuentra, debe permitir ingresar el teléfono correspondiente.
 * **Buscar**: Nos pide una cadena de caracteres, y nos muestras todos los contactos cuyos nombres comiencen por dicha cadena.
 * **Borrar**: Nos pide un nombre y si existe nos preguntará si queremos borrarlo de la agenda.
 * **Listar**: Nos muestra todos los contactos de la agenda.

  Implementar el script con un diccionario.

In [ ]:
# Escribir un programa que implemente una agenda. En la agenda se podrán guardar nombres y números de teléfono.
# El programa nos dará el siguiente menú:
#
# * Añadir/modificar: Nos pide un nombre. Si el nombre se encuentra en la agenda, debe mostrar el teléfono y,
# opcionalmente, permitir modificarlo si no es correcto. Si el nombre no se encuentra, debe
# permitir ingresar el teléfono correspondiente.
# * Buscar: Nos pide una cadena de caracteres, y nos muestras todos los contactos cuyos nombres comiencen por dicha cadena.
# * Borrar: Nos pide un nombre y si existe nos preguntará si queremos borrarlo de la agenda.
# * Listar: Nos muestra todos los contactos de la agenda.
#
# Implementar el programa con un diccionario.

agenda = {}
opcion = 0
while opcion != 5:
    print("\n")
    print("1. Añadir/modificar")
    print("2. Buscar")
    print("3. Borrar")
    print("4. Listar")
    print("5. Salir")

    opcion = int(input("Dime opción:"))
    match opcion:
      case 1:
        nombre = input("Nombre del contacto:")
        if nombre in agenda:
            print("%s ya existe su número de teléfono es %s" % (nombre,agenda[nombre]))
            opcion = input("Pulsa 's' si quieres modificarlo!!!. Otra tecla para continuar.")
            if opcion == "s":
                numero = input("Dame el nuevo número de teléfono:")
                agenda[nombre]=numero
        else:
            numero = input("Dame el número de teléfono:")
            agenda[nombre]=numero
      case 2:
        cadena = input("Nombre del contacto a buscar:")
        for nombre, numero in agenda.items():
            if nombre.startswith(cadena):
                print("El número de teléfono de %s es el %s" % (nombre,agenda[nombre]))
      case 3:
        nombre = input("Nombre del contacto para borrar:")
        if nombre in agenda:
            opcion = input("Pulsa 's' si quieres borrarlo!!!. Otra tecla para continuar.")
            if opcion == "s":
                del agenda[nombre]
        else:
            print("No existe el contacto")
      case 4:
        for nombre, numero in agenda.items():
            print(nombre,"->",numero)
      case 5:
        print("\n Adiós.")
      case _:
        print("Opción incorrecta")




1. Añadir/modificar
2. Buscar
3. Borrar
4. Listar
5. Salir
Dime opción:4


1. Añadir/modificar
2. Buscar
3. Borrar
4. Listar
5. Salir
Dime opción:5

 Adiós.


9. Crear un script que al introducir una fecha nos diga a que día juliano corresponde. El día juliano correspondiente a una fecha es un número entero que indica los días que han transcurrido desde el 1 de enero.Para ello debes de hacer las siguientes funciones:
 * **LeerFecha**: Lee por teclado el día, mes y el año.
 * **DiasDelMes**: Recibe un mes y un año y devuelve el número de días
 * **EsBisiesto**: Recibido un año nos dice si es bisiesto o no.
 * **Calcular_Dia_Juliano**: Recibe una fecha y nos devuelve el día juliano.

In [ ]:
def LeerFecha():
  dia = int(input("Introduce el día: "))
  mes = int(input("Introduce el mes: "))
  año = int(input("Introduce el año: "))
  return dia, mes, año

def DiasDelMes(mes, año):
  if mes in [1, 3, 5, 7, 8, 10, 12]:
   return 31
  elif mes in [4, 6, 9, 11]:
   return 30
  elif mes == 2:
   if EsBisiesto(año):
    return 29
   else:
    return 28

def EsBisiesto(año):
  if (año % 4 == 0 and año % 100 != 0) or (año % 400 == 0):
   return True
  else:
   return False

def Calcular_Dia_Juliano(dia, mes, año):
  total_dias = dia
  for m in range(1, mes):
   total_dias += DiasDelMes(m, año)
  return total_dias

# Programa principal
fecha = LeerFecha()
dia_juliano = Calcular_Dia_Juliano(fecha[0], fecha[1], fecha[2])
print("El día juliano correspondiente a la fecha es:", dia_juliano)

MJD de 2025-01-01: 2460707
MJD de 2025-03-01: 2460676
Días transcurridos desde 2025-01-01: 32



10. Función CalcularMCD: Recibe dos números y devuelve el MCD utilizando el método de Euclides.
El método de Euclides es el siguiente:
 * Se divide el número mayor entre el menor.
 * Si la división es exacta, el divisor es el MCD.
 * Si la división no es exacta, dividimos el divisor entre el resto obtenido y se continúa de esta forma hasta obtener una división exacta, siendo el último divisor el MCD.


In [ ]:
def mcd(a,b):
    if a < 0:
        return mcd(-a,b)
    if b < 0:
        return mcd(a,-b)
    if b == 0:
        return a #CASO BASE
    return mcd(a, a%b)
mcd(64,24)

64

In [ ]:
#Hacer un programa donde se pida un nombre por teclado y se imprima “Hola ..el_nombre_ingresado”
def holamun(nombre):
  print (f"Hola {nombre}")



holamun(nombre)
print(" ")

def nums(num1,num2):
  print(f"La suma es: {num1 + num2}")
  print(f"La resta es: {num1 - num2}")
  print(f"La multiplicación es: {num1 * num2}")
  print(f"La división es: {num1 / num2}")


num1 = int(input("Pasa el primer número: "))
num2 = int(input("Pasa el segundo número: "))
nums(num1,num2)
print(" ")

Hola Manolo
 
Pasa el primer número: 1
Pasa el segundo número: 2
La suma es: 3
La resta es: -1
La multiplicación es: 2
La división es: 0.5
 


In [ ]:
def LeerFecha():
    fec = str(input('Introduce una fecha YYYY-MM-DD: '))


def Calcular_Dia_Juliano(fec):

  from datetime import datetime
  from astropy.time import Time

  # Definir las fechas
  fecha_inicial = Time('2025-01-01')
  fecha_final = Time(datetime.strptime(fec, '%Y-%m-%d'))

  # Calcular los MJD
  mjd_inicial = fecha_inicial.jd
  mjd_final = fecha_final.jd

  # Calcular la diferencia en días desde 2025-01-01
  dias_transcurridos = round(mjd_final) - round(mjd_inicial)

  # Resultados
  print(f"Días transcurridos desde 2025-01-01: {dias_transcurridos}")

# Programa principal
LeerFecha()
dia_juliano = Calcular_Dia_Juliano(fec)


Introduce una fecha YYYY-MM-DD: 2025-09-21
Días transcurridos desde 2025-01-01: 128


In [ ]:
import numpy as np
n=6
array = np.array([[i*n+j for j in range(n)] for i in range(n)])
det = np.linalg.det(array)
print(array)
print(det)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
0.0


In [ ]:
#Hacer un programa donde se pida un nombre por teclado y se imprima “Hola ..el_nombre_ingresado”
def holamun(nombre):
  print (f"Hola {nombre}")



holamun(nombre)
print(" ")

def nums(num1,num2):
  print(f"La suma es: {num1 + num2}")
  print(f"La resta es: {num1 - num2}")
  print(f"La multiplicación es: {num1 * num2}")
  print(f"La división es: {num1 / num2}")


num1 = int(input("Pasa el primer número: "))
num2 = int(input("Pasa el segundo número: "))
nums(num1,num2)
print(" ")